=== aunimhsn/xml-course/app/db/bibliography.dtd
<!ELEMENT bibliography (book+)>
<!ELEMENT book (title,author,year,publisher,isbn,url?)>
<!ATTLIST book id NMTOKEN #REQUIRED>
<!ATTLIST book lang NMTOKEN #IMPLIED>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT publisher (#PCDATA)>
<!ELEMENT isbn (#PCDATA)>
<!ELEMENT url (#PCDATA)>

=== aunimhsn/xml-course/app/db/bibliography.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bibliography SYSTEM "bibliography.dtd">
<bibliography>
    <book id="1">
        <title>XML langage et applications</title>
        <author>Alain Michard</author>
        <year>2001</year>
        <publisher>Eyrolles</publisher>
        <isbn>2-212-09206-7</isbn>
        <url>http://www.editions-eyrolles/livres/michard/</url>
    </book>
    <book id="2" lang="fr">
        <title>XML by Example</title>
        <author>Beno√Æt Marchal</author>
        <year>2000</year>
        <publisher>Macmillan Computer Publishing</publisher>
        <isbn>0-7897-2242-9</isbn>
    </book>
</bibliography>
